# Generated by Django 6.0.1 on 2026-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("transport", "Transport"),
                    ("subscriptions", "Subscriptions"),
                    ("shopping", "Shopping"),
                    ("entertainment", "Entertainment"),
                    ("utilities", "Utilities"),
                    ("school", "School"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
